### ISSUE TITLE
Lightbox on /artworks/artwork-id

### ISSUE THREAD

**Issue by radicleart** [radicleart/brightblock-oam#17]
Added mdb vue lightbox to the artwork page.

**Comment by antonijask** [comment]
This is great.

Since we have a Lightbox now where a user can enlarge the image can we make the one on the artwork page to fit the size?
https://radicle.art/#/artworks/1552407117082
![artworkpage-img](https://user-images.githubusercontent.com/47831018/54527073-142ee980-4979-11e9-9fc2-264f64caaeb3.png)
